### PR TITLE
Full theme upgrade for a future version 1.0.3

### PR DESCRIPTION
**Pull request by pmoreno-rodriguez**
Hello. I have done a deep review of the theme, which I have been doing for some time and now I think it is ready to be released in the next version of the theme. The changes included are the following:

   * Added modular Banner template
   * Added modular Recent Posts template
   * Added modular Contact template
   * Added modular Features template
   * Added Forms templates
   * Added blueprints for default, blog, item, and modulars templates.
   * Added partials templates: blog-list-item, logo, metadata and simplesearch_searchbox
   * Added Item template
   * Added Modular template
   * Added Error template
   * Added Simplesearch Results template
   * Added functionality to searchbox in sidebar
   * Added Production mode for CSS styles.
   * Added Custom logo and Custom logo mobile in theme config.
   * Improved the languages.yaml file and added the Spanish language
   * Improved all blueprints to support language translation
   * Improved the featured posts template in the sidebar, to use a taxonomy chosen by the user and not the default `featured`. A limit of posts that will appear is also established.
   * Rolling back assets to original HTML5Up version, to fix Fontawesome fonts.

### CODE REVIEW

**Comment by pmoreno-rodriguez** [comment]
You can view a demo in [http://editorial.juanvillen.es/](http://editorial.juanvillen.es/)

**Comment by jgonyea** [comment]
Wow, what a tremendous amount of work.  Thank you

**Comment by pmoreno-rodriguez** [comment]
Hi. I like very much the Editorial Theme, and I'd like to be a contributor in your repository. What you think?.

**Comment by jgonyea** [comment]
@pmoreno-rodriguez, would you like to take it over?  I have next to no time due to my $DAYJOB to work on this, and would be happy to transfer the official theme to you

**Comment by pmoreno-rodriguez** [comment]
Alright @jgonyea , I might as well take over this topic so I can keep it. Thanks for trusting me.

**Comment by jgonyea** [comment]
I've submitted an issue to transfer the gpm link to your fork

**Comment by rhukster** [comment]
done on my end.

**Comment by pmoreno-rodriguez** [comment]
Thanks @jgonyea and @rhukster.

**Comment by pmoreno-rodriguez** [comment]
Hi @jgonyea.

I'm still learning a lot about GitHub and Git. I would like to know how I should proceed now. My repository still shows up as a Fork of the original, and I can't create Releases. Also, all changes are still checked against the main branch of original repository.

Can you give me a hand to continue with the work?

**Comment by pmoreno-rodriguez** [comment]
I've found this hello on the internet

**Comment by pmoreno-rodriguez** [comment]
I've found this tip on Internet:

1. Clone the repo somewhere:

git clone git@github.com:USERNAME/REPOSITORY.git

(make double sure you have it cloned)

2. Delete the repo in GitHub (Settings > Options > Delete this repository)

3. Create a new blank repo in GitHub

4. git remote set-url origin git@github.com:USERNAME/NEW_REPOSITORY.git
(if you used the same name for the repo, then NEW_REPOSITORY == REPOSITORY 👍🏻)

git push

Is this the best way to setup the Editorial the as the main repository in my GitHub profile?

Thanks in advance.

**Comment by jgonyea** [comment]
I think that all makes sense.  Ping me once you've double checked you have your repo local and I'll delete mine from github

**Comment by pmoreno-rodriguez** [comment]
Ok.
I will do it as soon as possible. As soon as I verify that everything is correct and GPM updates the theme on the Grav theme page, I ping you.

**Pull request merged**
